INSERT INTO echoesoftheheart.dialogos (capitulo_id,tipo,url_fondo,url_musica,personaje_id,esconder,html,php,orden_origen,orden_destino,es_opcion) VALUES
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Despierta.',NULL,1,2,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Escucho una suave voz que atraviesa la oscuridad.)',NULL,2,3,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','No lo haré dos veces. Despierta.',NULL,3,4,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Abro los ojos lentamente. La pantalla se desvanece del negro, y frente a mí aparece un paisaje. Una mujer está de pie al fondo, observándome.)',NULL,4,5,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Así está mejor. Te has hecho esperar, y aunque no soy conocida por mi paciencia, me aseguraré de que entiendas por qué estás aquí.',NULL,5,6,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Soy Amaranta y a ti te llaman [Nombre del usuario]. No me mires así, lo sé todo sobre ti. Eres quien debía llegar. Por eso estoy aquí, y por eso el bosque ha guardado silencio hasta ahora.',NULL,6,7,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Este lugar… este momento… no es un accidente. Pero antes de explicarte lo que necesitas saber, hay algo que debes decidir: ¿quieres avanzar o prefieres quedarte en esta ignorancia reconfortante?',NULL,7,8,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Siento el peso de su mirada, esperando mi respuesta.)',NULL,8,9,0),
	 (1,'eleccion','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','Quiero saber más.',NULL,9,11,1),
	 (1,'eleccion','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','No confío en ti.',NULL,9,15,1);
INSERT INTO echoesoftheheart.dialogos (capitulo_id,tipo,url_fondo,url_musica,personaje_id,esconder,html,php,orden_origen,orden_destino,es_opcion) VALUES
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Sabia decisión. Aunque el conocimiento es un peso, también es la clave para sobrevivir aquí. Presta atención: cada acción que tomes tendrá consecuencias.',NULL,11,12,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Siento que el aire se hace más denso, como si todo lo que está por suceder dependiera de mi decisión.)',NULL,12,13,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Levántate, vamos a ponerte a prueba. Te daré dos lugares para elegir, y en cada uno encontrarás diferentes escenarios. Vuelve cuando hayas terminado. Recuerda: una vez escojas un camino, no podrás retroceder.',NULL,13,14,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Amaranta me extiende la mano, y por un momento dudo. El futuro parece incierto, pero la decisión es mía.)',NULL,14,19,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','La confianza no es necesaria, solo la acción. Sin embargo, si deseas caminar a ciegas, no puedo detenerte. Pero recuerda: el bosque no perdona a los indecisos.',NULL,15,16,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Siento su presencia como una sombra sobre mí. Aunque sus palabras son duras, no tengo opción más que seguir adelante.)',NULL,16,17,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Amaranta da un paso atrás, y veo su mano extendida hacia mí.)',NULL,17,18,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Levántate. Hay mucho que aprender y poco tiempo. Te guiaré, pero dependerá de ti elegir correctamente. No falles, [Nombre del usuario]. Ahora, escoge.',NULL,18,19,0),
	 (1,'eleccion','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',1,'','Derecha.',NULL,19,21,1),
	 (1,'eleccion','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',1,'','Izquierda.',NULL,19,33,1);
INSERT INTO echoesoftheheart.dialogos (capitulo_id,tipo,url_fondo,url_musica,personaje_id,esconder,html,php,orden_origen,orden_destino,es_opcion) VALUES
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',2,'','Ah, interesante eleccion. Pero no todo lo que brilla es seguro. Adelante, acércate con cuidado. Estoy observando.',NULL,21,22,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',1,'2','(Dudo por un momento, pero decido acercarme. A medida que avanzo, la figura se gira lentamente. Es un hombre alto, con una mirada severa. Su armadura espartana y la lanza que lleva en la mano me dicen que no es alguien con quien deba jugar. Él frunce el ceño al verme.)',NULL,22,23,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',3,'2','¿Quién eres y por qué estás aquí? Habla rápido, o conocerás el filo de mi lanza.',NULL,23,24,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',1,'2','(Siento la tensión en el aire. Mi cuerpo se tensa, pero antes de poder reaccionar, una figura aparece entre nosotros. Es Amaranta, tan tranquila como siempre, y se coloca entre el guerrero y yo.)',NULL,24,25,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',2,'','Detente, Ajax. Este no es un intruso cualquiera.',NULL,25,26,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',1,'','(Ajax parece vacilar, pero aún mantiene su postura defensiva, sin bajar la lanza.)',NULL,26,27,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',3,'','Amaranta. ¿Qué juego estás jugando? No confiaré en nadie que traigas aquí.',NULL,27,28,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',2,'','No te estoy pidiendo confianza, guerrero. Solo respeto. Este viajero no está listo para enfrentarse a ti. Déjalo pasar.',NULL,28,29,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_2.jpg','about:blank',3,'','Llévalo de vuelta contigo, Amaranta. Y dile que no cruce este umbral de nuevo, a menos que venga preparado."',NULL,29,30,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'','Volvamos. Aquí no hay nada para ti todavía.',NULL,30,31,0);
INSERT INTO echoesoftheheart.dialogos (capitulo_id,tipo,url_fondo,url_musica,personaje_id,esconder,html,php,orden_origen,orden_destino,es_opcion) VALUES
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',1,'','(Amaranta me toma del brazo y me guía hacia un portal de luz que aparece en la pared del templo.)',NULL,31,32,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',2,'','Tu eleccion fue interesante. No hay caminos correctos o incorrectos, solo lecciones que aprender. Ahora sabes lo que te espera allí. Guarda ese conocimiento, te será útil.',NULL,32,44,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/img_Escena/imagen_helio.png','about:blank',1,'todos','(El escenario cambia a un bosque, y el jugador se encuentra sola hasta que ve algo.)','$user = \App\Models\User::find(Auth::id());

$user->imagenes()->attach(1);',33,34,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',2,'','Ah, buena eleccion. Este camino tiene sus propias sorpresas, pero no todas las sorpresas son malas. ¿Por qué no te acercas? Vamos.',NULL,34,35,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',1,'2','(Decido acercarme con cautela. Al hacerlo, la figura se vuelve hacia mí. Es un hombre joven, con cabello desordenado y ojos brillantes. Está vestido con ropa sencilla pero elegante, y parece completamente absorbido en la música que toca. Cuando nota mi presencia, sonríe amablemente.)',NULL,35,36,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',4,'2','Oh, una compañía inesperada. Qué fortuna para mí. Me temo que el bosque puede ser un lugar solitario para un alma errante. ¿Qué te trae por aquí?',NULL,36,37,0),
	 (1,'eleccion','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',1,'2','Estoy explorando.',NULL,37,39,1),
	 (1,'eleccion','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',1,'2','¿Quién eres tú?',NULL,37,40,1),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',4,'2','Un espíritu curioso, ya veo. Estos bosques son generosos con aquellos que se atreven a caminar por ellos. Pero cuidado, no todos los encuentros serán tan... pacíficos como este.',NULL,39,41,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',4,'2','¿Quién soy? Qué pregunta tan compleja para un hombre simple como yo. Puedes llamarme Elio. Solo un viajero, como tú.',NULL,40,41,0);
INSERT INTO echoesoftheheart.dialogos (capitulo_id,tipo,url_fondo,url_musica,personaje_id,esconder,html,php,orden_origen,orden_destino,es_opcion) VALUES
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/background_3.jpg','about:blank',1,'2','(Me siento a gusto en su presencia, pero la voz de Amaranta irrumpe nuevamente.)',NULL,41,42,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,NULL,'Es suficiente por ahora. No olvides que este bosque no es tuyo, y cada minuto aquí tiene un precio. Volvamos al inicio.',NULL,42,43,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'','(Elio asiente y vuelve a su laúd, tocando una melodía suave. Amaranta, sin perder el ritmo, me hace un gesto y un portal de luz aparece entre los árboles. Lo sigo mientras el paisaje cambia rápidamente de vuelta al claro inicial del bosque.)',NULL,43,44,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'3.4','(Cuando llegamos al punto de partida, Amaranta me observa fijamente.)',NULL,44,45,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'3.4','No estuvo mal, pero no te dejes llevar por lo que parezca amable. Incluso las flores más hermosas pueden ser venenosas. Continúa aprendiendo.',NULL,45,46,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'3.4','(Amaranta me observa en silencio por un momento, como si estuviera esperando algo más de mí. El aire en el claro parece más denso, y el silencio se vuelve pesado.)',NULL,46,47,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'3.4','Cada eleccion que tomes será un reflejo de lo que eres. Y aunque el camino que escogiste tiene sus propias lecciones, hay algo más que aún no ves.',NULL,47,48,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'3.4','(Siento que lo que he elegido hasta ahora ha sido solo una pequeña muestra de lo que vendrá. Mis decisiones me han llevado hasta aquí, y todo a mi alrededor parece estar esperándome.)',NULL,48,49,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'3.4','Lo que has presenciado es solo el principio. Recuerda, [Nombre del usuario], este bosque no es solo un lugar físico, sino una prueba. Y la prueba apenas comienza.',NULL,49,50,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'3.4','(Sus palabras se sienten como una advertencia y una invitación al mismo tiempo. Cada paso que dé a partir de aquí definirá algo más grande que yo.)',NULL,50,51,0);
INSERT INTO echoesoftheheart.dialogos (capitulo_id,tipo,url_fondo,url_musica,personaje_id,esconder,html,php,orden_origen,orden_destino,es_opcion) VALUES
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'3.4','El tiempo no espera, y tus acciones no serán olvidadas. Has elegido un camino, y no hay forma de regresar, pero lo que hagas a partir de ahora es lo que te guiará.',NULL,51,52,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'3.4','(Me siento decidida, pero también abrumada por la incertidumbre del futuro. Amaranta me observa, como si esperara que comprendiera completamente lo que está en juego.)',NULL,52,53,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',2,'3.4','Cada camino que tomes cambiará no solo lo que te rodea, sino también lo que llevas dentro. Así que, ¿estás listo para avanzar, [Nombre del usuario]?',NULL,53,54,0),
	 (1,'texto','https://echoesoftheheart.subpolygon.com/media_juego/fondos/fondo.png','about:blank',1,'3.4','(Terminar capitulo.)',NULL,54,NULL,0);
